### ISSUE TITLE
Keycode issue

### ISSUE THREAD

**Issue by ginolee218** [UBIQCONN/imx-android-11#1]
when i press key 189, 190, 191, it also trigger key 23(dpad center)

16:08:43.105 17804-17804 BaseActivity                        com.ubiqconn.iphs.yahsat        D  onKeyDown: 189
16:08:43.107 17804-17804 BaseActivity                        com.ubiqconn.iphs.yahsat        D  onKeyDown: 23

16:08:51.773 17804-17804 BaseActivity                        com.ubiqconn.iphs.yahsat        D  onKeyDown: 190
16:08:51.774 17804-17804 BaseActivity                        com.ubiqconn.iphs.yahsat        D  onKeyDown: 23

16:08:54.800 17804-17804 BaseActivity                        com.ubiqconn.iphs.yahsat        D  onKeyDown: 191
16:08:54.801 17804-17804 BaseActivity                        com.ubiqconn.iphs.yahsat        D  onKeyDown: 23

**Comment by ShihYuan-Huang** [comment]
Fix in this https://github.com/UBIQCONN/uti-linux-imx/commit/219a9cd7dd3d809def6922f45de1f5277e305e4f

**Comment by ginolee218** [comment]
one short press

09:38:30.791         D  dispatchKeyEvent: 189, getAction: onKeyDown, getRepeatCount: 0
09:38:30.794         D  dispatchKeyEvent: 23, getAction: onKeyDown, getRepeatCount: 0
09:38:30.951         D  dispatchKeyEvent: 189, getAction: onKeyUp, getRepeatCount: 0

09:42:50.758         D  dispatchKeyEvent: 191, getAction: onKeyDown, getRepeatCount: 0
09:42:50.761         D  dispatchKeyEvent: 23, getAction: onKeyDown, getRepeatCount: 0
09:42:50.873         D  dispatchKeyEvent: 191, getAction: onKeyUp, getRepeatCount: 0

=================================================================
long presee

09:48:56.031         D  dispatchKeyEvent: 189, getAction: onKeyDown, getRepeatCount: 0
09:48:56.031         D  setScreenBrightness: 100
09:48:56.039         D  dispatchKeyEvent: 23, getAction: onKeyDown, getRepeatCount: 0
09:48:56.431         D  dispatchKeyEvent: 23, getAction: onKeyDown, getRepeatCount: 1
09:48:56.481         D  dispatchKeyEvent: 23, getAction: onKeyDown, getRepeatCount: 2
09:48:56.531         D  dispatchKeyEvent: 23, getAction: onKeyDown, getRepeatCount: 3
09:48:56.581         D  dispatchKeyEvent: 23, getAction: onKeyDown, getRepeatCount: 4
09:48:56.632         D  dispatchKeyEvent: 23, getAction: onKeyDown, getRepeatCount: 5
09:48:56.975         D  dispatchKeyEvent: 189, getAction: onKeyUp, getRepeatCount: 0
09:48:57.007         D  dispatchKeyEvent: 23, getAction: onKeyUp, getRepeatCount: 0


09:45:33.075        D  dispatchKeyEvent: 191, getAction: onKeyDown, getRepeatCount: 0
09:45:33.082        D  dispatchKeyEvent: 23, getAction: onKeyDown, getRepeatCount: 0
09:45:33.476        D  dispatchKeyEvent: 23, getAction: onKeyDown, getRepeatCount: 1
09:45:33.526        D  dispatchKeyEvent: 23, getAction: onKeyDown, getRepeatCount: 2
09:45:33.576        D  dispatchKeyEvent: 23, getAction: onKeyDown, getRepeatCount: 3
09:45:33.626        D  dispatchKeyEvent: 23, getAction: onKeyDown, getRepeatCount: 4
09:45:33.676        D  dispatchKeyEvent: 23, getAction: onKeyDown, getRepeatCount: 5
09:45:34.018        D  dispatchKeyEvent: 191, getAction: onKeyUp, getRepeatCount: 0
09:45:34.020        D  dispatchKeyEvent: 23, getAction: onKeyUp, getRepeatCount: 0
